### PR TITLE
Optimize steim 1 and 2 decoders

### PR DESCRIPTION
**Pull request by chad-earthscope**
Approach taken:

* Avoid potential pointer dereferencing
* Remove unnecessary values, write directly to output array
* Simplify loops, allow compiler to unroll or vectorize as it sees fit
* Remove run-time check for debugging output, now compile-time options (same for packing)

### CODE REVIEW

**Comment by chad-earthscope** [comment]
Test program for steim levels 1 and 2 decoding:
[decode_rodeo.c.zip](https://github.com/EarthScope/libmseed/files/11918886/decode_rodeo.c.zip)

The program runs the decoders in a timed loop with variable iterations.

**Comment by chad-earthscope** [comment]
Test OS: macOS 13.4.1
CPU: 2.4 GHz Core i9
compiler: Apple clang version 14.0.3
test program command: `./decode_rodeo -i 1000000`

| Decoder | Optimization | Original (6f5add8e3b55009d21a05abb6154e9ef324f1252) | PR #90 | This PR (e0b21aa8f51ecd7f1bc6dd7929cddcc1d036258a) |
| --- | --- | --- | --- | --- |
| Steim-2 | -O0 | 8.4 seconds | 7.9 s | 7.2 s |
| Steim-1 | -O0 | 7.0 seconds | 7.7 s | 6.5 s |
| Steim-2 | -O2 | 1.7 seconds | 1.98 s | 1.1 s |
| Steim-1 | -O3 | 1.8 seconds | 1.57 s| 0.97 s|

@Cuda-Chen Above includes test results for your PR.  I would be grateful if you could confirm the results.

**Comment by Cuda-Chen** [comment]
Hi @chad-earthscope ,
below table shows the results of the execution time comparison on my computer:

| Decoder | Optimization | Original (6f5add8) | This PR (e0b21aa) |
| -- | -- | -- | -- |
| Steim-2 | `-O0` | 7.50 seconds | 7.65 seconds |
| Steim-1 | `-O0` | 5.86 seconds | 5.82 seconds |
| Steim-2 | `-O2` | 2.24 seconds | 2.23 seconds |
| Steim-1 | `-O2` | 2.46 seconds | 1.76 seconds |
| Steim-2 | `-O3` | 2.79 seconds | 2.16 seconds |
| Steim-1 | `-O3` | 1.91 seconds |1.68 seconds |

## Test Specification
- CPU: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
- OS: Linux 5.15.0-76
- compiler: GCC 11.3.0

## Test Procedures
1. Unzip `decode_rodeo.c.zip` in repo's root directory.
2. Add `decode_rodeo.c` in `LIB_SRCS` located in Makefile in repo's root directory.
3. Run `make`.
4. Run `gcc -o decode_rodeo *.o` to create `decode_rodeo` executable.
5. Run `./decode_rodeo` with the following procedures:
  -- Run `./decode_rodeo -i 1000000` three times. Each time, record the execution time of Steim-1 and Steim-2 decoding then count the average execution, respectively.
  -- Change the optimization flag in Makefile located in repo's root directory.
 6. Repeat 3. to 5.

**Comment by chad-earthscope** [comment]
Thanks @Cuda-Chen.  Not as much general improvement as I'd hoped, I'm surprised at very little improvement at `Steim-2 @ -O2`.

I think I'll go with this change unless you have time soon to work on it further.

**Comment by Cuda-Chen** [comment]
I agree. Let's work on this PR.

**Comment by chad-earthscope** [comment]
More test results for different platforms.  Same procedure as used by @Cuda-Chen, average of 3 runs for each measurement.

linux 5.15.0-76
Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz
gcc version 11.3.0 

| encoding | optimization | develop | #102  |
| -------- | ------------ | ------- | ----- |
| S2       |  -O0         | 7.76s   | 6.86s |
| S1       |  -O0         | 5.78s   | 5.3s |
| S2       |  -O2         | 2.06s   | 1.95s |
| S1       |  -O2         | 2.25s   | 1.55s |

linux 5.15.0-76
Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
gcc version 11.3.0

| encoding | optimization | develop | #102  |
| -------- | ------------ | ------- | ----- |
| S2       |  -O0         | 15.8s   | 13.8s |
| S1       |  -O0         | 12.34s  | 10.8s |
| S2       |  -O2         | 5.0s    | 4.35s |
| S1       |  -O2         | 4.5s    | 3.5s  |

linux 5.10.103-v7
armv7l / Cortex-A53
gcc version 10.2.1 20210110 (Raspbian 10.2.1-6+rpi1)

| encoding | optimization | develop | #102  |
| -------- | ------------ | ------- | ----- |
| S2       |  -O0         | 63.5s   | 54.5s |
| S1       |  -O0         | 50.5s   | 45.4s |
| S2       |  -O2         | 16.5s   | 13.2s |
| S1       |  -O2         | 13.9s   | 11.9s |



Not a drastic improvement, but varying between 5-30% reduction in run times, and a consistent improvement in each case.

Given all of the above results, I'm going to merge this for a stable release.  We can continue to work on improvements in another PR.

**Pull request merged**
